halotroop2288 references
fabric-community/MCDrama pull request #19
Opened 2020-02-15 07:51 UTC by halotroop2288

Feel free to make suggestions about this
I just want to be a part of it. :)

2020-02-15 22:45 UTC, valoeghese requested changes

2020-02-15 22:45 UTC, valoeghese commented on data/mod
> +Ex-Features
The one in mod needs to match the one in author for it to work

2020-02-15 22:46 UTC, valoeghese commented
Also fix merge conflicts

2020-02-16 04:42 UTC, halotroop2288 reviewed
Should be all fixed now.

2020-02-16 10:17 UTC, merged